plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

group 'com.jjordanoc.azure_speech_recognition_null_safety'
version '1.0-SNAPSHOT'

def speechSdkVersion = project.findProperty("AZURE_SPEECH_SDK_VERSION") ?: "1.48.2"

android {
    namespace 'com.jjordanoc.azure_speech_recognition_null_safety'
    compileSdk 37

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        minSdk 26
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
    }

    lint {
        disable.add('InvalidPackage')
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

dependencies {
    implementation "com.microsoft.cognitiveservices.speech:client-sdk:$speechSdkVersion"
}
